// Generated by scripts/build-sources.mjs. Do not edit.
import type {VideoSchema} from './contract';
import {showreelSchema as showreelV1Schema} from '../legacy/showreel/v1/showreel/schema';
import {stackSchema as stackV1Schema} from '../legacy/stack/v1/stack/schema';
import {tickerSchema as tickerV1Schema} from '../legacy/ticker/v1/ticker/schema';
import {terminalSchema as terminalV1Schema} from '../legacy/terminal/v1/terminal/schema';
import {pulseSchema as pulseV1Schema} from '../legacy/pulse/v1/pulse/schema';
import {folioSchema as folioV1Schema} from '../legacy/folio/v1/folio/schema';
import {bentoSchema as bentoV1Schema} from '../legacy/bento/v1/bento/schema';
import {glassSchema as glassV1Schema} from '../legacy/glass/v1/glass/schema';
import {flexSchema as flexV1Schema} from '../legacy/flex/v1/flex/schema';
import {risoSchema as risoV1Schema} from '../legacy/riso/v1/riso/schema';
import {collageSchema as collageV1Schema} from '../legacy/collage/v1/collage/schema';
import {cursorSchema as cursorV1Schema} from '../legacy/cursor/v1/cursor/schema';
import {spotlightSchema as spotlightV1Schema} from '../legacy/spotlight/v1/spotlight/schema';
import {sliceSchema as sliceV1Schema} from '../legacy/slice/v1/slice/schema';
import {swissSchema as swissV1Schema} from '../legacy/swiss/v1/swiss/schema';
import {prismSchema as prismV1Schema} from '../legacy/prism/v1/prism/schema';
import {lowerthirdSchema as lowerthirdV1Schema} from '../legacy/lowerthird/v1/lowerthird/schema';
import {kineticSchema as kineticV1Schema} from '../legacy/kinetic/v1/kinetic/schema';
import {endscreenSchema as endscreenV1Schema} from '../legacy/endscreen/v1/endscreen/schema';
import {blackfridaySchema as blackfridayV1Schema} from '../legacy/blackfriday/v1/blackfriday/schema';
import {wordmarkSchema as wordmarkV1Schema} from '../legacy/wordmark/v1/wordmark/schema';
import {testimonialSchema as testimonialV1Schema} from '../legacy/testimonial/v1/testimonial/schema';
import {ytintroSchema as ytintroV1Schema} from '../legacy/ytintro/v1/ytintro/schema';
import {wrappedSchema as wrappedV1Schema} from '../legacy/wrapped/v1/wrapped/schema';
import {countdownSchema as countdownV1Schema} from '../legacy/countdown/v1/countdown/schema';
import {podcastSchema as podcastV1Schema} from '../legacy/podcast/v1/podcast/schema';

export const legacySchemas: Record<string, Record<number, VideoSchema>> = {
  showreel: {1: showreelV1Schema as unknown as VideoSchema},
  stack: {1: stackV1Schema as unknown as VideoSchema},
  ticker: {1: tickerV1Schema as unknown as VideoSchema},
  terminal: {1: terminalV1Schema as unknown as VideoSchema},
  pulse: {1: pulseV1Schema as unknown as VideoSchema},
  folio: {1: folioV1Schema as unknown as VideoSchema},
  bento: {1: bentoV1Schema as unknown as VideoSchema},
  glass: {1: glassV1Schema as unknown as VideoSchema},
  flex: {1: flexV1Schema as unknown as VideoSchema},
  riso: {1: risoV1Schema as unknown as VideoSchema},
  collage: {1: collageV1Schema as unknown as VideoSchema},
  cursor: {1: cursorV1Schema as unknown as VideoSchema},
  spotlight: {1: spotlightV1Schema as unknown as VideoSchema},
  slice: {1: sliceV1Schema as unknown as VideoSchema},
  swiss: {1: swissV1Schema as unknown as VideoSchema},
  prism: {1: prismV1Schema as unknown as VideoSchema},
  lowerthird: {1: lowerthirdV1Schema as unknown as VideoSchema},
  kinetic: {1: kineticV1Schema as unknown as VideoSchema},
  endscreen: {1: endscreenV1Schema as unknown as VideoSchema},
  blackfriday: {1: blackfridayV1Schema as unknown as VideoSchema},
  wordmark: {1: wordmarkV1Schema as unknown as VideoSchema},
  testimonial: {1: testimonialV1Schema as unknown as VideoSchema},
  ytintro: {1: ytintroV1Schema as unknown as VideoSchema},
  wrapped: {1: wrappedV1Schema as unknown as VideoSchema},
  countdown: {1: countdownV1Schema as unknown as VideoSchema},
  podcast: {1: podcastV1Schema as unknown as VideoSchema},
};
