// Generated by scripts/build-sources.mjs. Do not edit.
import type {TemplateMeta, VideoSchema} from './contract';
import type React from 'react';


export type LegacyDef = TemplateMeta & {component: React.FC<any>; schema: VideoSchema};
export const legacy: Record<string, Record<number, LegacyDef>> = {

};
