// Generated by scripts/build-sources.mjs. Do not edit.
import type {TemplateMeta, VideoSchema} from './contract';
import type React from 'react';
import {Showreel as showreelV1} from '../legacy/showreel/v1/showreel/Showreel';
import {showreelMeta as showreelV1Meta} from '../legacy/showreel/v1/showreel/meta';
import {showreelSchema as showreelV1Schema} from '../legacy/showreel/v1/showreel/schema';
import {Stack as stackV1} from '../legacy/stack/v1/stack/Stack';
import {stackMeta as stackV1Meta} from '../legacy/stack/v1/stack/meta';
import {stackSchema as stackV1Schema} from '../legacy/stack/v1/stack/schema';
import {Ticker as tickerV1} from '../legacy/ticker/v1/ticker/Ticker';
import {tickerMeta as tickerV1Meta} from '../legacy/ticker/v1/ticker/meta';
import {tickerSchema as tickerV1Schema} from '../legacy/ticker/v1/ticker/schema';
import {Terminal as terminalV1} from '../legacy/terminal/v1/terminal/Terminal';
import {terminalMeta as terminalV1Meta} from '../legacy/terminal/v1/terminal/meta';
import {terminalSchema as terminalV1Schema} from '../legacy/terminal/v1/terminal/schema';
import {Pulse as pulseV1} from '../legacy/pulse/v1/pulse/Pulse';
import {pulseMeta as pulseV1Meta} from '../legacy/pulse/v1/pulse/meta';
import {pulseSchema as pulseV1Schema} from '../legacy/pulse/v1/pulse/schema';
import {Folio as folioV1} from '../legacy/folio/v1/folio/Folio';
import {folioMeta as folioV1Meta} from '../legacy/folio/v1/folio/meta';
import {folioSchema as folioV1Schema} from '../legacy/folio/v1/folio/schema';
import {Bento as bentoV1} from '../legacy/bento/v1/bento/Bento';
import {bentoMeta as bentoV1Meta} from '../legacy/bento/v1/bento/meta';
import {bentoSchema as bentoV1Schema} from '../legacy/bento/v1/bento/schema';
import {Glass as glassV1} from '../legacy/glass/v1/glass/Glass';
import {glassMeta as glassV1Meta} from '../legacy/glass/v1/glass/meta';
import {glassSchema as glassV1Schema} from '../legacy/glass/v1/glass/schema';
import {Flex as flexV1} from '../legacy/flex/v1/flex/Flex';
import {flexMeta as flexV1Meta} from '../legacy/flex/v1/flex/meta';
import {flexSchema as flexV1Schema} from '../legacy/flex/v1/flex/schema';
import {Riso as risoV1} from '../legacy/riso/v1/riso/Riso';
import {risoMeta as risoV1Meta} from '../legacy/riso/v1/riso/meta';
import {risoSchema as risoV1Schema} from '../legacy/riso/v1/riso/schema';
import {Collage as collageV1} from '../legacy/collage/v1/collage/Collage';
import {collageMeta as collageV1Meta} from '../legacy/collage/v1/collage/meta';
import {collageSchema as collageV1Schema} from '../legacy/collage/v1/collage/schema';
import {Cursor as cursorV1} from '../legacy/cursor/v1/cursor/Cursor';
import {cursorMeta as cursorV1Meta} from '../legacy/cursor/v1/cursor/meta';
import {cursorSchema as cursorV1Schema} from '../legacy/cursor/v1/cursor/schema';
import {Spotlight as spotlightV1} from '../legacy/spotlight/v1/spotlight/Spotlight';
import {spotlightMeta as spotlightV1Meta} from '../legacy/spotlight/v1/spotlight/meta';
import {spotlightSchema as spotlightV1Schema} from '../legacy/spotlight/v1/spotlight/schema';
import {Slice as sliceV1} from '../legacy/slice/v1/slice/Slice';
import {sliceMeta as sliceV1Meta} from '../legacy/slice/v1/slice/meta';
import {sliceSchema as sliceV1Schema} from '../legacy/slice/v1/slice/schema';
import {Swiss as swissV1} from '../legacy/swiss/v1/swiss/Swiss';
import {swissMeta as swissV1Meta} from '../legacy/swiss/v1/swiss/meta';
import {swissSchema as swissV1Schema} from '../legacy/swiss/v1/swiss/schema';
import {Prism as prismV1} from '../legacy/prism/v1/prism/Prism';
import {prismMeta as prismV1Meta} from '../legacy/prism/v1/prism/meta';
import {prismSchema as prismV1Schema} from '../legacy/prism/v1/prism/schema';
import {Lowerthird as lowerthirdV1} from '../legacy/lowerthird/v1/lowerthird/Lowerthird';
import {lowerthirdMeta as lowerthirdV1Meta} from '../legacy/lowerthird/v1/lowerthird/meta';
import {lowerthirdSchema as lowerthirdV1Schema} from '../legacy/lowerthird/v1/lowerthird/schema';
import {Kinetic as kineticV1} from '../legacy/kinetic/v1/kinetic/Kinetic';
import {kineticMeta as kineticV1Meta} from '../legacy/kinetic/v1/kinetic/meta';
import {kineticSchema as kineticV1Schema} from '../legacy/kinetic/v1/kinetic/schema';
import {Endscreen as endscreenV1} from '../legacy/endscreen/v1/endscreen/Endscreen';
import {endscreenMeta as endscreenV1Meta} from '../legacy/endscreen/v1/endscreen/meta';
import {endscreenSchema as endscreenV1Schema} from '../legacy/endscreen/v1/endscreen/schema';
import {Blackfriday as blackfridayV1} from '../legacy/blackfriday/v1/blackfriday/Blackfriday';
import {blackfridayMeta as blackfridayV1Meta} from '../legacy/blackfriday/v1/blackfriday/meta';
import {blackfridaySchema as blackfridayV1Schema} from '../legacy/blackfriday/v1/blackfriday/schema';
import {Wordmark as wordmarkV1} from '../legacy/wordmark/v1/wordmark/Wordmark';
import {wordmarkMeta as wordmarkV1Meta} from '../legacy/wordmark/v1/wordmark/meta';
import {wordmarkSchema as wordmarkV1Schema} from '../legacy/wordmark/v1/wordmark/schema';
import {Testimonial as testimonialV1} from '../legacy/testimonial/v1/testimonial/Testimonial';
import {testimonialMeta as testimonialV1Meta} from '../legacy/testimonial/v1/testimonial/meta';
import {testimonialSchema as testimonialV1Schema} from '../legacy/testimonial/v1/testimonial/schema';
import {Ytintro as ytintroV1} from '../legacy/ytintro/v1/ytintro/Ytintro';
import {ytintroMeta as ytintroV1Meta} from '../legacy/ytintro/v1/ytintro/meta';
import {ytintroSchema as ytintroV1Schema} from '../legacy/ytintro/v1/ytintro/schema';
import {Wrapped as wrappedV1} from '../legacy/wrapped/v1/wrapped/Wrapped';
import {wrappedMeta as wrappedV1Meta} from '../legacy/wrapped/v1/wrapped/meta';
import {wrappedSchema as wrappedV1Schema} from '../legacy/wrapped/v1/wrapped/schema';
import {Countdown as countdownV1} from '../legacy/countdown/v1/countdown/Countdown';
import {countdownMeta as countdownV1Meta} from '../legacy/countdown/v1/countdown/meta';
import {countdownSchema as countdownV1Schema} from '../legacy/countdown/v1/countdown/schema';
import {Podcast as podcastV1} from '../legacy/podcast/v1/podcast/Podcast';
import {podcastMeta as podcastV1Meta} from '../legacy/podcast/v1/podcast/meta';
import {podcastSchema as podcastV1Schema} from '../legacy/podcast/v1/podcast/schema';

export type LegacyDef = TemplateMeta & {component: React.FC<any>; schema: VideoSchema};
export const legacy: Record<string, Record<number, LegacyDef>> = {
  showreel: {1: {...showreelV1Meta, component: showreelV1, schema: showreelV1Schema as unknown as VideoSchema}},
  stack: {1: {...stackV1Meta, component: stackV1, schema: stackV1Schema as unknown as VideoSchema}},
  ticker: {1: {...tickerV1Meta, component: tickerV1, schema: tickerV1Schema as unknown as VideoSchema}},
  terminal: {1: {...terminalV1Meta, component: terminalV1, schema: terminalV1Schema as unknown as VideoSchema}},
  pulse: {1: {...pulseV1Meta, component: pulseV1, schema: pulseV1Schema as unknown as VideoSchema}},
  folio: {1: {...folioV1Meta, component: folioV1, schema: folioV1Schema as unknown as VideoSchema}},
  bento: {1: {...bentoV1Meta, component: bentoV1, schema: bentoV1Schema as unknown as VideoSchema}},
  glass: {1: {...glassV1Meta, component: glassV1, schema: glassV1Schema as unknown as VideoSchema}},
  flex: {1: {...flexV1Meta, component: flexV1, schema: flexV1Schema as unknown as VideoSchema}},
  riso: {1: {...risoV1Meta, component: risoV1, schema: risoV1Schema as unknown as VideoSchema}},
  collage: {1: {...collageV1Meta, component: collageV1, schema: collageV1Schema as unknown as VideoSchema}},
  cursor: {1: {...cursorV1Meta, component: cursorV1, schema: cursorV1Schema as unknown as VideoSchema}},
  spotlight: {1: {...spotlightV1Meta, component: spotlightV1, schema: spotlightV1Schema as unknown as VideoSchema}},
  slice: {1: {...sliceV1Meta, component: sliceV1, schema: sliceV1Schema as unknown as VideoSchema}},
  swiss: {1: {...swissV1Meta, component: swissV1, schema: swissV1Schema as unknown as VideoSchema}},
  prism: {1: {...prismV1Meta, component: prismV1, schema: prismV1Schema as unknown as VideoSchema}},
  lowerthird: {1: {...lowerthirdV1Meta, component: lowerthirdV1, schema: lowerthirdV1Schema as unknown as VideoSchema}},
  kinetic: {1: {...kineticV1Meta, component: kineticV1, schema: kineticV1Schema as unknown as VideoSchema}},
  endscreen: {1: {...endscreenV1Meta, component: endscreenV1, schema: endscreenV1Schema as unknown as VideoSchema}},
  blackfriday: {1: {...blackfridayV1Meta, component: blackfridayV1, schema: blackfridayV1Schema as unknown as VideoSchema}},
  wordmark: {1: {...wordmarkV1Meta, component: wordmarkV1, schema: wordmarkV1Schema as unknown as VideoSchema}},
  testimonial: {1: {...testimonialV1Meta, component: testimonialV1, schema: testimonialV1Schema as unknown as VideoSchema}},
  ytintro: {1: {...ytintroV1Meta, component: ytintroV1, schema: ytintroV1Schema as unknown as VideoSchema}},
  wrapped: {1: {...wrappedV1Meta, component: wrappedV1, schema: wrappedV1Schema as unknown as VideoSchema}},
  countdown: {1: {...countdownV1Meta, component: countdownV1, schema: countdownV1Schema as unknown as VideoSchema}},
  podcast: {1: {...podcastV1Meta, component: podcastV1, schema: podcastV1Schema as unknown as VideoSchema}},
};
