import records from './records.json' with {type: 'json'};
import type {AssetRecord} from '../../media/catalog';

// Generated by scripts/generate-assets.mjs. Prompts are in prompts.json; records hold the exact output.
export const photolowerAssets = records as AssetRecord[];
